# 환경변수 모으기

import os

# 노션에 연결중인 현재가 DB의 토큰값.
NOTION_TOKEN = os.environ["NOTION_TOKEN"]

# 국내주식 종목 DB 링크
NOTION_DOMESTIC_STOCK_INFO_DB_ID = os.environ["NOTION_DOMESTIC_STOCK_INFO_DB_ID"]

# 국내주식 거래내역 DB 링크
NOTION_DOMESTIC_STOCK_TRADE_DB_ID = os.environ["NOTION_DOMESTIC_STOCK_TRADE_DB_ID"]

# 국내주식 배당금 DB 링크
NOTION_DOMESTIC_STOCK_DIVIDEND_DB_ID = os.environ["NOTION_DOMESTIC_STOCK_DIVIDEND_DB_ID"]

# KRX 금현물 종목 DB 링크
NOTION_KRX_GOLD_INFO_DB_ID = os.environ["NOTION_KRX_GOLD_INFO_DB_ID"]

# KRX 금현물 거래내역 DB 링크
NOTION_KRX_GOLD_TRADE_DB_ID = os.environ["NOTION_KRX_GOLD_TRADE_DB_ID"]

# 국내 채권 ETF 종목 DB 링크
NOTION_DOMESTIC_BOND_ETF_INFO_DB_ID = os.environ["NOTION_DOMESTIC_BOND_ETF_INFO_DB_ID"]

# 국내 채권 ETF 거래내역 DB 링크
NOTION_DOMESTIC_BOND_ETF_TRADE_DB_ID = os.environ["NOTION_DOMESTIC_BOND_ETF_TRADE_DB_ID"]

# 순수익 DB 링크
NOTION_NET_PROFIT_DB_ID = os.environ["NOTION_NET_PROFIT_DB_ID"]
